// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/cosmos/state-mesh/pkg/types"
)

type ChainAccountState struct {
	ChainName    string              `json:"chainName"`
	AccountState *types.AccountState `json:"accountState"`
}

type ChainValidators struct {
	ChainName  string             `json:"chainName"`
	Validators []*types.Validator `json:"validators"`
}

type CrossChainValidators struct {
	Validators []*ChainValidators `json:"validators"`
}

type DenomAmount struct {
	Denom  string `json:"denom"`
	Amount string `json:"amount"`
}

type Query struct {
}
